// Replace the driveUrl values with your actual Google Drive share links
// You can also point to entire folders so users can browse

export const notes = [
  // Class 9 Notes
  {
    id: 'n-9-math-ch1',
    title: 'Class 9 Maths - Number Systems',
    subject: 'Mathematics',
    class: '9',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-1',
  },
  {
    id: 'n-9-sci-phy',
    title: 'Class 9 Science - Physics Notes',
    subject: 'Physics',
    class: '9',
    type: 'Subject Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-2',
  },
  {
    id: 'n-9-eng-lit',
    title: 'Class 9 English - Literature Notes',
    subject: 'English',
    class: '9',
    type: 'Literature Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-3',
  },
  {
    id: 'n-9-sst-hist',
    title: 'Class 9 Social Studies - History',
    subject: 'History',
    class: '9',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-4',
  },
  {
    id: 'n-9-math-sol',
    title: 'Class 9 Maths - Number Systems Solutions',
    subject: 'Mathematics',
    class: '9',
    type: 'Solutions',
    driveUrl: 'https://drive.google.com/your-notes-link-5',
  },
  {
    id: 'n-9-ref-1',
    title: 'Class 9 Mathematics Reference Guide',
    subject: 'Mathematics',
    class: '9',
    type: 'Reference Materials',
    driveUrl: 'https://drive.google.com/your-notes-link-6',
  },

  // Class 10 Notes
  {
    id: 'n-10-math-ch1',
    title: 'Class 10 Maths - Real Numbers',
    subject: 'Mathematics',
    class: '10',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-7',
  },
  {
    id: 'n-10-sci-chem',
    title: 'Class 10 Science - Chemistry Notes',
    subject: 'Chemistry',
    class: '10',
    type: 'Subject Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-8',
  },
  {
    id: 'n-10-eng-gram',
    title: 'Class 10 English - Grammar Notes',
    subject: 'English',
    class: '10',
    type: 'Grammar Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-9',
  },
  {
    id: 'n-10-sst-geo',
    title: 'Class 10 Social Studies - Geography',
    subject: 'Geography',
    class: '10',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-10',
  },
  {
    id: 'n-10-math-sol',
    title: 'Class 10 Maths - Real Numbers Solutions',
    subject: 'Mathematics',
    class: '10',
    type: 'Solutions',
    driveUrl: 'https://drive.google.com/your-notes-link-11',
  },
  {
    id: 'n-10-ref-1',
    title: 'Class 10 Science Reference Materials',
    subject: 'Science',
    class: '10',
    type: 'Reference Materials',
    driveUrl: 'https://drive.google.com/your-notes-link-12',
  },

  // Class 11 Notes
  {
    id: 'n-11-phy-ch1',
    title: 'Class 11 Physics - Physical World',
    subject: 'Physics',
    class: '11',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-13',
  },
  {
    id: 'n-11-chem-ch1',
    title: 'Class 11 Chemistry - Some Basic Concepts',
    subject: 'Chemistry',
    class: '11',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-14',
  },
  {
    id: 'n-11-math-ch1',
    title: 'Class 11 Maths - Sets',
    subject: 'Mathematics',
    class: '11',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-15',
  },
  {
    id: 'n-11-bio-ch1',
    title: 'Class 11 Biology - The Living World',
    subject: 'Biology',
    class: '11',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-16',
  },
  {
    id: 'n-11-phy-sol',
    title: 'Class 11 Physics - Physical World Solutions',
    subject: 'Physics',
    class: '11',
    type: 'Solutions',
    driveUrl: 'https://drive.google.com/your-notes-link-17',
  },
  {
    id: 'n-11-ref-1',
    title: 'Class 11 Chemistry Reference Guide',
    subject: 'Chemistry',
    class: '11',
    type: 'Reference Materials',
    driveUrl: 'https://drive.google.com/your-notes-link-18',
  },

  // Class 12 Notes
  {
    id: 'n-12-phy-ch2',
    title: 'Class 12 Physics - Electrostatics',
    subject: 'Physics',
    class: '12',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-19',
  },
  {
    id: 'n-12-chem-ch1',
    title: 'Class 12 Chemistry - Solutions',
    subject: 'Chemistry',
    class: '12',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-20',
  },
  {
    id: 'n-12-math-ch1',
    title: 'Class 12 Maths - Relations and Functions',
    subject: 'Mathematics',
    class: '12',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-21',
  },
  {
    id: 'n-12-bio-ch1',
    title: 'Class 12 Biology - Reproduction in Organisms',
    subject: 'Biology',
    class: '12',
    type: 'Chapter Notes',
    driveUrl: 'https://drive.google.com/your-notes-link-22',
  },
  {
    id: 'n-12-math-sol',
    title: 'Class 12 Maths - Relations and Functions Solutions',
    subject: 'Mathematics',
    class: '12',
    type: 'Solutions',
    driveUrl: 'https://drive.google.com/your-notes-link-23',
  },
  {
    id: 'n-12-ref-1',
    title: 'Class 12 Physics Reference Materials',
    subject: 'Physics',
    class: '12',
    type: 'Reference Materials',
    driveUrl: 'https://drive.google.com/your-notes-link-24',
  },

  // JKBOSE Official Textbooks - Class 9
  {
    id: 'jkb-9-english',
    title: 'Class 9 English Textbook',
    subject: 'English',
    class: '9',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass9.html',
  },
  {
    id: 'jkb-9-hindi',
    title: 'Class 9 Hindi Textbook',
    subject: 'Hindi',
    class: '9',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass9.html',
  },
  {
    id: 'jkb-9-math',
    title: 'Class 9 Mathematics Textbook',
    subject: 'Mathematics',
    class: '9',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass9.html',
  },
  {
    id: 'jkb-9-science',
    title: 'Class 9 Science Textbook',
    subject: 'Science',
    class: '9',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass9.html',
  },
  {
    id: 'jkb-9-social',
    title: 'Class 9 Social Studies Textbook',
    subject: 'Social Studies',
    class: '9',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass9.html',
  },

  // JKBOSE Official Textbooks - Class 10
  {
    id: 'jkb-10-english',
    title: 'English Part-I',
    subject: 'English',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/PageDoc/English%20Class%2010th-1.pdf',
  },
  {
    id: 'jkb-10-english2',
    title: 'English Part-II',
    subject: 'English',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/PageDoc/English%20Class%2010th-2.pdf',
  },
  {
    id: 'jkb-10-urdu',
    title: 'Urdu',
    subject: 'Urdu',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/PageDoc/Urdu%2010th-2024.pdf',
  },
  {
    id: 'jkb-10-hindi',
    title: 'Hindi',
    subject: 'Hindi',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/pdf/Class10thhindi.pdf',
  },
  {
    id: 'jkb-10-kashmiri',
    title: 'Kashmiri',
    subject: 'Kashmiri',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/pdf/Class10thKashmiri.pdf',
  },
  
  {
    id: 'jkb-10-math1',
    title: 'Mathematics-I',
    subject: 'Mathematics',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/PageDoc/Math%2010th%20Part%20A%20-2024.pdf',
  },
  {
    id: 'jkb-10-math2',
    title: 'Mathematics-II',
    subject: 'Mathematics',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/PageDoc/Math%2010th%20Part%20B-2024.pdf',
  },
  {
    id: 'jkb-10-science',
    title: 'Science',
    subject: 'Science',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/pdf/Class%2010th%20Science.pdf',
  },
  {
    id: 'jkb-10-social',
    title: 'Class 10 Social Studies Textbook',
    subject: 'Social Studies',
    class: '10',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass10.html',
  },
  

  // JKBOSE Official Textbooks - Class 11
  {
    id: 'jkb-11-physics',
    title: 'Class 11 Physics Textbook',
    subject: 'Physics',
    class: '11',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass11.html',
  },
  {
    id: 'jkb-11-chemistry',
    title: 'Class 11 Chemistry Textbook',
    subject: 'Chemistry',
    class: '11',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass11.html',
  },
  {
    id: 'jkb-11-mathematics',
    title: 'Class 11 Mathematics Textbook',
    subject: 'Mathematics',
    class: '11',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass11.html',
  },
  {
    id: 'jkb-11-biology',
    title: 'Class 11 Biology Textbook',
    subject: 'Biology',
    class: '11',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass11.html',
  },
  {
    id: 'jkb-11-english',
    title: 'Class 11 English Textbook',
    subject: 'English',
    class: '11',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass11.html',
  },

  // JKBOSE Official Textbooks - Class 12
  {
    id: 'jkb-12-physics',
    title: 'Class 12 Physics Textbook',
    subject: 'Physics',
    class: '12',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass12.html',
  },
  {
    id: 'jkb-12-chemistry',
    title: 'Class 12 Chemistry Textbook',
    subject: 'Chemistry',
    class: '12',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass12.html',
  },
  {
    id: 'jkb-12-mathematics',
    title: 'Class 12 Mathematics Textbook',
    subject: 'Mathematics',
    class: '12',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass12.html',
  },
  {
    id: 'jkb-12-biology',
    title: 'Class 12 Biology Textbook',
    subject: 'Biology',
    class: '12',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass12.html',
  },
  {
    id: 'jkb-12-english',
    title: 'Class 12 English Textbook',
    subject: 'English',
    class: '12',
    type: 'JKBOSE Textbook',
    driveUrl: 'https://jkbose.nic.in/textbookclass12.html',
  },
]

export const papers = [
  // Class 9 Papers
  {
    id: 'p-9-math-2023',
    title: 'Class 9 Mathematics 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Mathematics',
    class: '9',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-1',
  },
  {
    id: 'p-9-sci-2023',
    title: 'Class 9 Science 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Science',
    class: '9',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-2',
  },

  // Class 10 Papers
  {
    id: 'p-10-math-2023',
    title: 'Class 10 Mathematics 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Mathematics',
    class: '10',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-3',
  },
  {
    id: 'p-10-sci-2023',
    title: 'Class 10 Science 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Science',
    class: '10',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-4',
  },
  {
    id: 'p-10-eng-2023',
    title: 'Class 10 English 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'English',
    class: '10',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-5',
  },

  // Class 11 Papers
  {
    id: 'p-11-phy-2023',
    title: 'Class 11 Physics 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Physics',
    class: '11',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-6',
  },
  {
    id: 'p-11-chem-2023',
    title: 'Class 11 Chemistry 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Chemistry',
    class: '11',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-7',
  },
  {
    id: 'p-11-math-2023',
    title: 'Class 11 Mathematics 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Mathematics',
    class: '11',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-8',
  },

  // Class 12 Papers
  {
    id: 'p-12-phy-2023',
    title: 'Class 12 Physics 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Physics',
    class: '12',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-9',
  },
  {
    id: 'p-12-chem-2023',
    title: 'Class 12 Chemistry 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Chemistry',
    class: '12',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-10',
  },
  {
    id: 'p-12-math-2023',
    title: 'Class 12 Mathematics 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Mathematics',
    class: '12',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-11',
  },
  {
    id: 'p-12-bio-2023',
    title: 'Class 12 Biology 2023',
    subtitle: 'Previous Year Paper (PDF)',
    subject: 'Biology',
    class: '12',
    year: '2023',
    driveUrl: 'https://drive.google.com/your-papers-link-12',
  },
]

export const books = [
  // Class 9 Books
  {
    id: 'b-9-math',
    title: 'Class 9 Mathematics Textbook',
    subtitle: 'JKBOSE Official',
    class: '9',
    subject: 'Mathematics',
    driveUrl: 'https://drive.google.com/your-books-link-1',
  },
  {
    id: 'b-9-sci',
    title: 'Class 9 Science Textbook',
    subtitle: 'JKBOSE Official',
    class: '9',
    subject: 'Science',
    driveUrl: 'https://drive.google.com/your-books-link-2',
  },
  {
    id: 'b-9-eng',
    title: 'Class 9 English Textbook',
    subtitle: 'JKBOSE Official',
    class: '9',
    subject: 'English',
    driveUrl: 'https://drive.google.com/your-books-link-3',
  },

  // Class 10 Books
  {
    id: 'b-10-math',
    title: 'Class 10 Mathematics Textbook',
    subtitle: 'JKBOSE Official',
    class: '10',
    subject: 'Mathematics',
    driveUrl: 'https://drive.google.com/your-books-link-4',
  },
  {
    id: 'b-10-sci',
    title: 'Class 10 Science Textbook',
    subtitle: 'JKBOSE Official',
    class: '10',
    subject: 'Science',
    driveUrl: 'https://drive.google.com/your-books-link-5',
  },
  {
    id: 'b-10-eng',
    title: 'Class 10 English Textbook',
    subtitle: 'JKBOSE Official',
    class: '10',
    subject: 'English',
    driveUrl: 'https://drive.google.com/your-books-link-6',
  },

  // Class 11 Books
  {
    id: 'b-11-phy',
    title: 'Class 11 Physics Textbook',
    subtitle: 'JKBOSE Official',
    class: '11',
    subject: 'Physics',
    driveUrl: 'https://drive.google.com/your-books-link-7',
  },
  {
    id: 'b-11-chem',
    title: 'Class 11 Chemistry Textbook',
    subtitle: 'JKBOSE Official',
    class: '11',
    subject: 'Chemistry',
    driveUrl: 'https://drive.google.com/your-books-link-8',
  },
  {
    id: 'b-11-math',
    title: 'Class 11 Mathematics Textbook',
    subtitle: 'JKBOSE Official',
    class: '11',
    subject: 'Mathematics',
    driveUrl: 'https://drive.google.com/your-books-link-9',
  },
  {
    id: 'b-11-bio',
    title: 'Class 11 Biology Textbook',
    subtitle: 'JKBOSE Official',
    class: '11',
    subject: 'Biology',
    driveUrl: 'https://drive.google.com/your-books-link-10',
  },

  // Class 12 Books
  {
    id: 'b-12-phy',
    title: 'Class 12 Physics Textbook',
    subtitle: 'JKBOSE Official',
    class: '12',
    subject: 'Physics',
    driveUrl: 'https://drive.google.com/your-books-link-11',
  },
  {
    id: 'b-12-chem',
    title: 'Class 12 Chemistry Textbook',
    subtitle: 'JKBOSE Official',
    class: '12',
    subject: 'Chemistry',
    driveUrl: 'https://drive.google.com/your-books-link-12',
  },
  {
    id: 'b-12-math',
    title: 'Class 12 Mathematics Textbook',
    subtitle: 'JKBOSE Official',
    class: '12',
    subject: 'Mathematics',
    driveUrl: 'https://drive.google.com/your-books-link-13',
  },
  {
    id: 'b-12-bio',
    title: 'Class 12 Biology Textbook',
    subtitle: 'JKBOSE Official',
    class: '12',
    subject: 'Biology',
    driveUrl: 'https://drive.google.com/your-books-link-14',
  },
]

export const images = [
  // Class 9 Images
  {
    id: 'i-9-math-diagrams',
    title: 'Class 9 Mathematics Diagrams',
    subtitle: 'Geometric figures and graphs',
    class: '9',
    subject: 'Mathematics',
    driveUrl: 'https://drive.google.com/your-images-link-1',
  },
  {
    id: 'i-9-sci-diagrams',
    title: 'Class 9 Science Diagrams',
    subtitle: 'Physics, Chemistry & Biology diagrams',
    class: '9',
    subject: 'Science',
    driveUrl: 'https://drive.google.com/your-images-link-2',
  },

  // Class 10 Images
  {
    id: 'i-10-math-diagrams',
    title: 'Class 10 Mathematics Diagrams',
    subtitle: 'Trigonometry and geometry diagrams',
    class: '10',
    subject: 'Mathematics',
    driveUrl: 'https://drive.google.com/your-images-link-3',
  },
  {
    id: 'i-10-sci-diagrams',
    title: 'Class 10 Science Diagrams',
    subtitle: 'Physics, Chemistry & Biology diagrams',
    class: '10',
    subject: 'Science',
    driveUrl: 'https://drive.google.com/your-images-link-4',
  },

  // Class 11 Images
  {
    id: 'i-11-phy-diagrams',
    title: 'Class 11 Physics Diagrams',
    subtitle: 'Mechanics and thermodynamics diagrams',
    class: '11',
    subject: 'Physics',
    driveUrl: 'https://drive.google.com/your-images-link-5',
  },
  {
    id: 'i-11-chem-diagrams',
    title: 'Class 11 Chemistry Diagrams',
    subtitle: 'Molecular structures and reactions',
    class: '11',
    subject: 'Chemistry',
    driveUrl: 'https://drive.google.com/your-images-link-6',
  },
  {
    id: 'i-11-bio-diagrams',
    title: 'Class 11 Biology Diagrams',
    subtitle: 'Cell structures and organisms',
    class: '11',
    subject: 'Biology',
    driveUrl: 'https://drive.google.com/your-images-link-7',
  },

  // Class 12 Images
  {
    id: 'i-12-phy-diagrams',
    title: 'Class 12 Physics Diagrams',
    subtitle: 'Electromagnetism and optics diagrams',
    class: '12',
    subject: 'Physics',
    driveUrl: 'https://drive.google.com/your-images-link-8',
  },
  {
    id: 'i-12-chem-diagrams',
    title: 'Class 12 Chemistry Diagrams',
    subtitle: 'Organic chemistry and polymers',
    class: '12',
    subject: 'Chemistry',
    driveUrl: 'https://drive.google.com/your-images-link-9',
  },
  {
    id: 'i-12-bio-diagrams',
    title: 'Class 12 Biology Diagrams',
    subtitle: 'Genetics and ecology diagrams',
    class: '12',
    subject: 'Biology',
    driveUrl: 'https://drive.google.com/your-images-link-10',
  },
]


