// StudiBOSE Resource Data
// Structure: { class: { notes: [], books: [], papers: [], images: [] } }

  // Class 11 Books
// New resources export
export const resources = {
  class10: {
    books: [
      {
        id: 'jkb-10-english',
        title: 'English Part-I',
        subject: 'English',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/PageDoc/English%20Class%2010th-1.pdf',
      },
      {
        id: 'jkb-10-english2',
        title: 'English Part-II',
        subject: 'English',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/PageDoc/English%20Class%2010th-2.pdf',
      },
      {
        id: 'jkb-10-urdu',
        title: 'Urdu',
        subject: 'Urdu',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/PageDoc/Urdu%2010th-2024.pdf',
      },
      {
        id: 'jkb-10-hindi',
        title: 'Hindi',
        subject: 'Hindi',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class10thhindi.pdf',
      },
      {
        id: 'jkb-10-kashmiri',
        title: 'Kashmiri',
        subject: 'Kashmiri',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class10thKashmiri.pdf',
      },
      {
        id: 'jkb-10-math1',
        title: 'Mathematics-I',
        subject: 'Mathematics',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/PageDoc/Math%2010th%20Part%20A%20-2024.pdf',
      },
      {
        id: 'jkb-10-math2',
        title: 'Mathematics-II',
        subject: 'Mathematics',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/PageDoc/Math%2010th%20Part%20B-2024.pdf',
      },
      {
        id: 'jkb-10-science',
        title: 'Science',
        subject: 'Science',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class%2010th%20Science.pdf',
      },
      {
        id: 'jkb-10-social',
        title: 'Class 10 Social Studies Textbook',
        subject: 'Social Studies',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/textbookclass10.html',
      },
      {
        id: 'jkb-10-history1',
        title: 'History Part-I',
        subject: 'History',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class%2010th%20History%20part-1.pdf',
      },
      {
        id: 'jkb-10-history2',
        title: 'History Part-II',
        subject: 'History',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class%2010th%20History%20part-2.pdf',
      },
      {
        id: 'jkb-10-history3',
        title: 'History Part-III',
        subject: 'History',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class%2010th%20History%20part-3.pdf',
      },
      {
        id: 'jkb-10-geography',
        title: 'Geography',
        subject: 'Geography',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class10thgeography.pdf',
      },
      {
        id: 'jkb-10-economics',
        title: 'Economics',
        subject: 'Economics',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/class10thdisastermanagement.pdf',
      },
      {
        id: 'jkb-10-democratic',
        title: 'Democratic Politics',
        subject: 'Democratic Politics',
        class: '10',
        type: 'JKBOSE Textbook',
        driveUrl: 'https://jkbose.nic.in/pdf/Class10thpoliticalscience.pdf',
      },
    ],
  },
  class11: {
    books: [],
  },
  class12: {
    images: [],
  },
};
